concurrent = 1

[[runners]]
  clone_url = "http://gitlab:80"
  name = "dind-runner"
  url = "http://gitlab:80"
  token = "${GITLAB_REGISTRATION_TOKEN}"
  executor = "docker"

  [runners.docker]
    image = "docker:27"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    shm_size = 256000000
    volumes = ["/cache"]
    extra_hosts = ["gitlab:172.50.0.10", "sonarqube:172.50.0.20", "minio:172.50.0.30"]

  [runners.cache]
    Type = "s3"
    Shared = true
    Path = "runner-cache"

    [runners.cache.s3]
      ServerAddress = "minio:9000"
      AccessKey = "${MINIO_ACCESS_KEY}"
      SecretKey = "${MINIO_SECRET_KEY}"
      BucketName = "gitlab-cache"
      BucketLocation = "eu-west-1"
      Insecure = true
