# GitLab CI configuration for the Users backend module

include:
  - local: 'infrastructure/configs/gitlab-ci-templates/ci-init.yml'
  - local: 'infrastructure/configs/gitlab-ci-templates/ci-stages.yml'
  - local: 'infrastructure/configs/gitlab-ci-templates/ci-build.yml'
  - local: 'infrastructure/configs/gitlab-ci-templates/ci-test.yml'
  - local: 'infrastructure/configs/gitlab-ci-templates/ci-quality.yml'
  - local: 'infrastructure/configs/gitlab-ci-templates/ci-security.yml'

variables:
  IMAGE_NAME: expense-manager-backend-users
  BASE_DIR_PATH: backend/users

# ----------------------
# cache configuration
# ----------------------

.dependency-check-cache: &dependency-check-cache
  key: dependency-check-data
  paths:
    - $BASE_DIR_PATH/dependency-check-data/

# ----------------------
# BUILD
# ----------------------

build:
  extends: .dotnet-build

# ----------------------
# TEST + COVERAGE
# ----------------------

test:
  extends: .dotnet-test

# ----------------------
# SONARQUBE ANALYSIS
# ----------------------

sonarqube:
  extends: .dotnet-sonarqube
  variables:
    SONAR_PROJECT_KEY: "touir:expense-manager:backend:users"

# ----------------------
# DOCKER BUILD
# ----------------------

docker-build:
  stage: docker
  image: docker:24
  services:
    - name: docker:24-dind
      command: ["--host=tcp://0.0.0.0:2375", "--insecure-registry=gitlab:5050", "--insecure-registry=172.50.0.10:5050"]
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  script:
    - echo "image = $CI_REGISTRY_IMAGE/$IMAGE_NAME:latest"
    - echo "Logging into registry = $CI_REGISTRY"
    - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u gitlab-ci-token --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE/$IMAGE_NAME:latest .
    - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME:latest

# ----------------------
# SCA – DEPENDENCY CHECK
# ----------------------

sca:
  extends: .sca
  variables:
    OWASP_PROJECT_NAME: "ExpenseManager-Backend-Users"
  cache:
    - *dependency-check-cache

# ----------------------
# SAST – SEMGREP
# ----------------------

sast:
  extends: .sast

# ----------------------
# SECRETS SCAN – GITLEAKS
# ----------------------
secrets-scan:
  stage: security
  image: 
    name: zricethezav/gitleaks:latest
    entrypoint: [""]
  script:
    - gitleaks detect --source . --no-git -c ../../.gitleaks.toml --report-format json --report-path gitleaks.json --verbose --platform gitlab
  artifacts:
    when: always
    paths:
      - $BASE_DIR_PATH/gitleaks.json

# ----------------------
# TRIVY IMAGE SCAN
# ----------------------
docker-security:
  stage: docker-security
  image: 
    name: aquasec/trivy:latest
    entrypoint: [""]
  dependencies:
    - docker-build
  services:
    - name: docker:24-dind
      command: ["--host=tcp://0.0.0.0:2375", "--insecure-registry=gitlab:5050", "--insecure-registry=172.50.0.10:5050"]
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
    TRIVY_USERNAME: "gitlab-ci-token"
    TRIVY_PASSWORD: "$CI_JOB_TOKEN"
    TRIVY_AUTH_URL: "$CI_REGISTRY"
    TRIVY_NO_PROGRESS: "true"
    TRIVY_CACHE_DIR: ".trivycache/"
    FULL_IMAGE_NAME: $CI_REGISTRY_IMAGE/$IMAGE_NAME:latest
    TRIVY_INSECURE: "true"
    TRIVY_NON_SSL: "true"
  script:
    - trivy --version
    # update vulnerabilities db
    - time trivy image --download-db-only
    # Builds report and puts it in the default workdir $CI_PROJECT_DIR, so `artifacts:` can take it from there
    - time trivy image --exit-code 0 --format template --template "@/contrib/gitlab.tpl" --output "gl-container-scanning-report.json" --ignorefile .trivyignore "$FULL_IMAGE_NAME"
    # Prints full report
    - time trivy image --exit-code 0 --ignorefile .trivyignore "$FULL_IMAGE_NAME"
    # Fail on critical vulnerabilities
    - time trivy image --exit-code 1 --severity CRITICAL --ignorefile .trivyignore "$FULL_IMAGE_NAME"
  cache:
    paths:
      - .trivycache/
  artifacts:
    when: always
    paths:
      - $BASE_DIR_PATH/gl-container-scanning-report.json
