# SonarQube configuration for the Dashboard frontend module

# project identification
sonar.projectKey=touir:expense-manager:backend:users
sonar.projectName=Expense Manager - Backend - Users

# Source and test directories
sonar.sources=Touir.ExpenseManager.Users
sonar.tests=Touir.ExpenseManager.Users.Tests

# Exclude test files and config from code quality analysis
sonar.exclusions=**/obj/**,**/bin/**,**/*.Designer.cs,**/*.g.cs

# Exclude test files and config from coverage calculations
sonar.coverage.exclusions=**/Program.cs,**/Startup.cs,**/*.Designer.cs,**/*.g.cs

# Coverage report path
sonar.cs.opencover.reportsPaths=coverage/**/*.opencover.xml
