CREATE USER expenses WITH PASSWORD 'expenses';
GRANT ALL PRIVILEGES ON DATABASE expenses to expenses;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO expenses;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO expenses;