CREATE USER expenses WITH PASSWORD 'expenses';
GRANT ALL PRIVILEGES ON DATABASE expenses to expenses;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO expenses;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO expenses;
GRANT ALL ON SCHEMA public TO expenses;
ALTER SCHEMA public OWNER TO expenses;
GRANT CREATE ON DATABASE expenses TO expenses;
