[supervisord]
nodaemon=true

[program:minio-sync]
command=/opt/jobs/scripts/minio-sync.sh
autostart=true
autorestart=true
stdout_logfile=/var/log/minio-sync.log
stderr_logfile=/var/log/minio-sync.err

[program:cron-runner]
command=/opt/jobs/scripts/cron-runner.sh
autostart=true
autorestart=true
stdout_logfile=/var/log/cron-runner.log
stderr_logfile=/var/log/cron-runner.err

[program:registry-proxy]
command=python3 /opt/jobs/scripts/registry_proxy.py /opt/jobs/configs/proxy_config.json
autostart=true
autorestart=true
stdout_logfile=/var/log/registry-proxy.log
stderr_logfile=/var/log/registry-proxy.err

[program:docker-image-updater-api]
command=bash /opt/jobs/scripts/docker-updater-runner.sh
environment=DOCKER_UPDATER_HTTP_API_TOKEN=%(ENV_DOCKER_UPDATER_HTTP_API_TOKEN)s,DOCKER_REGISTRY_USER=%(ENV_DOCKER_REGISTRY_USER)s,DOCKER_REGISTRY_TOKEN=%(ENV_DOCKER_REGISTRY_TOKEN)s,DOCKER_UPDATER_HTTP_API_PORT=%(ENV_DOCKER_UPDATER_HTTP_API_PORT)s
autostart=true
autorestart=true
stdout_logfile=/var/log/docker-image-updater-api.log
stderr_logfile=/var/log/docker-image-updater-api.err

[inet_http_server]                  ; inet (TCP) server, default disabled
port=0.0.0.0:9002                   ; ip:port for web UI
username=%(ENV_SUPERVISOR_USER)s    ; optional login
password=%(ENV_SUPERVISOR_PASS)s    ; optional password