using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Touir.ExpensesManager.Expenses.Migrations
{
    /// <inheritdoc />
    public partial class SeedCurrencies : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "Currencies",
                columns: new[] { "Id", "Code", "Name", "Decimals", "Symbol" },
                values: new object[,]
                {
                    {   1, "AED", "UAE Dirham",                              2, "د.إ"  },
                    {   2, "AFN", "Afghan Afghani",                          2, "؋"    },
                    {   3, "ALL", "Albanian Lek",                            2, "L"    },
                    {   4, "AMD", "Armenian Dram",                           2, "֏"    },
                    {   5, "ANG", "Netherlands Antillean Guilder",           2, "ƒ"    },
                    {   6, "AOA", "Angolan Kwanza",                          2, "Kz"   },
                    {   7, "ARS", "Argentine Peso",                          2, "$"    },
                    {   8, "AUD", "Australian Dollar",                       2, "$"    },
                    {   9, "AWG", "Aruban Florin",                           2, "ƒ"    },
                    {  10, "AZN", "Azerbaijani Manat",                       2, "₼"    },
                    {  11, "BAM", "Bosnia-Herzegovina Convertible Mark",     2, "KM"   },
                    {  12, "BBD", "Barbadian Dollar",                        2, "$"    },
                    {  13, "BDT", "Bangladeshi Taka",                        2, "৳"    },
                    {  14, "BGN", "Bulgarian Lev",                           2, "лв"   },
                    {  15, "BHD", "Bahraini Dinar",                          3, "BD"   },
                    {  16, "BIF", "Burundian Franc",                         0, "Fr"   },
                    {  17, "BMD", "Bermudian Dollar",                        2, "$"    },
                    {  18, "BND", "Brunei Dollar",                           2, "$"    },
                    {  19, "BOB", "Bolivian Boliviano",                      2, "Bs"   },
                    {  20, "BRL", "Brazilian Real",                          2, "R$"   },
                    {  21, "BSD", "Bahamian Dollar",                         2, "$"    },
                    {  22, "BTN", "Bhutanese Ngultrum",                      2, "Nu"   },
                    {  23, "BWP", "Botswana Pula",                           2, "P"    },
                    {  24, "BYN", "Belarusian Ruble",                        2, "Br"   },
                    {  25, "BZD", "Belize Dollar",                           2, "$"    },
                    {  26, "CAD", "Canadian Dollar",                         2, "$"    },
                    {  27, "CDF", "Congolese Franc",                         2, "Fr"   },
                    {  28, "CHF", "Swiss Franc",                             2, "Fr"   },
                    {  29, "CLP", "Chilean Peso",                            0, "$"    },
                    {  30, "CNY", "Chinese Yuan",                            2, "¥"    },
                    {  31, "COP", "Colombian Peso",                          2, "$"    },
                    {  32, "CRC", "Costa Rican Colón",                       2, "₡"    },
                    {  33, "CUP", "Cuban Peso",                              2, "$"    },
                    {  34, "CVE", "Cape Verdean Escudo",                     2, "$"    },
                    {  35, "CZK", "Czech Koruna",                            2, "Kč"   },
                    {  36, "DJF", "Djiboutian Franc",                        0, "Fr"   },
                    {  37, "DKK", "Danish Krone",                            2, "kr"   },
                    {  38, "DOP", "Dominican Peso",                          2, "$"    },
                    {  39, "DZD", "Algerian Dinar",                          2, "دج"   },
                    {  40, "EGP", "Egyptian Pound",                          2, "£"    },
                    {  41, "ERN", "Eritrean Nakfa",                          2, "Nfk"  },
                    {  42, "ETB", "Ethiopian Birr",                          2, "Br"   },
                    {  43, "EUR", "Euro",                                     2, "€"    },
                    {  44, "FJD", "Fijian Dollar",                           2, "$"    },
                    {  45, "FKP", "Falkland Islands Pound",                  2, "£"    },
                    {  46, "GBP", "British Pound Sterling",                  2, "£"    },
                    {  47, "GEL", "Georgian Lari",                           2, "₾"    },
                    {  48, "GHS", "Ghanaian Cedi",                           2, "₵"    },
                    {  49, "GIP", "Gibraltar Pound",                         2, "£"    },
                    {  50, "GMD", "Gambian Dalasi",                          2, "D"    },
                    {  51, "GNF", "Guinean Franc",                           0, "Fr"   },
                    {  52, "GTQ", "Guatemalan Quetzal",                      2, "Q"    },
                    {  53, "GYD", "Guyanese Dollar",                         2, "$"    },
                    {  54, "HKD", "Hong Kong Dollar",                        2, "$"    },
                    {  55, "HNL", "Honduran Lempira",                        2, "L"    },
                    {  56, "HTG", "Haitian Gourde",                          2, "G"    },
                    {  57, "HUF", "Hungarian Forint",                        2, "Ft"   },
                    {  58, "IDR", "Indonesian Rupiah",                       2, "Rp"   },
                    {  59, "ILS", "Israeli New Shekel",                      2, "₪"    },
                    {  60, "INR", "Indian Rupee",                            2, "₹"    },
                    {  61, "IQD", "Iraqi Dinar",                             3, "ع.د"  },
                    {  62, "IRR", "Iranian Rial",                            2, "﷼"    },
                    {  63, "ISK", "Icelandic Króna",                         0, "kr"   },
                    {  64, "JMD", "Jamaican Dollar",                         2, "$"    },
                    {  65, "JOD", "Jordanian Dinar",                         3, "JD"   },
                    {  66, "JPY", "Japanese Yen",                            0, "¥"    },
                    {  67, "KES", "Kenyan Shilling",                         2, "KSh"  },
                    {  68, "KGS", "Kyrgystani Som",                          2, "с"    },
                    {  69, "KHR", "Cambodian Riel",                          2, "៛"    },
                    {  70, "KMF", "Comorian Franc",                          0, "Fr"   },
                    {  71, "KPW", "North Korean Won",                        2, "₩"    },
                    {  72, "KRW", "South Korean Won",                        0, "₩"    },
                    {  73, "KWD", "Kuwaiti Dinar",                           3, "KD"   },
                    {  74, "KYD", "Cayman Islands Dollar",                   2, "$"    },
                    {  75, "KZT", "Kazakhstani Tenge",                       2, "₸"    },
                    {  76, "LAK", "Laotian Kip",                             2, "₭"    },
                    {  77, "LBP", "Lebanese Pound",                          2, "£"    },
                    {  78, "LKR", "Sri Lankan Rupee",                        2, "₨"    },
                    {  79, "LRD", "Liberian Dollar",                         2, "$"    },
                    {  80, "LSL", "Lesotho Loti",                            2, "L"    },
                    {  81, "LYD", "Libyan Dinar",                            3, "LD"   },
                    {  82, "MAD", "Moroccan Dirham",                         2, "MAD"  },
                    {  83, "MDL", "Moldovan Leu",                            2, "L"    },
                    {  84, "MGA", "Malagasy Ariary",                         2, "Ar"   },
                    {  85, "MKD", "Macedonian Denar",                        2, "ден"  },
                    {  86, "MMK", "Myanmar Kyat",                            2, "K"    },
                    {  87, "MNT", "Mongolian Tögrög",                        2, "₮"    },
                    {  88, "MOP", "Macanese Pataca",                         2, "P"    },
                    {  89, "MRU", "Mauritanian Ouguiya",                     2, "UM"   },
                    {  90, "MUR", "Mauritian Rupee",                         2, "₨"    },
                    {  91, "MVR", "Maldivian Rufiyaa",                       2, "Rf"   },
                    {  92, "MWK", "Malawian Kwacha",                         2, "MK"   },
                    {  93, "MXN", "Mexican Peso",                            2, "$"    },
                    {  94, "MYR", "Malaysian Ringgit",                       2, "RM"   },
                    {  95, "MZN", "Mozambican Metical",                      2, "MT"   },
                    {  96, "NAD", "Namibian Dollar",                         2, "$"    },
                    {  97, "NGN", "Nigerian Naira",                          2, "₦"    },
                    {  98, "NIO", "Nicaraguan Córdoba",                      2, "C$"   },
                    {  99, "NOK", "Norwegian Krone",                         2, "kr"   },
                    { 100, "NPR", "Nepalese Rupee",                          2, "₨"    },
                    { 101, "NZD", "New Zealand Dollar",                      2, "$"    },
                    { 102, "OMR", "Omani Rial",                              3, "ر.ع"  },
                    { 103, "PAB", "Panamanian Balboa",                       2, "B/."  },
                    { 104, "PEN", "Peruvian Sol",                            2, "S/"   },
                    { 105, "PGK", "Papua New Guinean Kina",                  2, "K"    },
                    { 106, "PHP", "Philippine Peso",                         2, "₱"    },
                    { 107, "PKR", "Pakistani Rupee",                         2, "₨"    },
                    { 108, "PLN", "Polish Złoty",                            2, "zł"   },
                    { 109, "PYG", "Paraguayan Guaraní",                      0, "₲"    },
                    { 110, "QAR", "Qatari Riyal",                            2, "QR"   },
                    { 111, "RON", "Romanian Leu",                            2, "lei"  },
                    { 112, "RSD", "Serbian Dinar",                           2, "din"  },
                    { 113, "RUB", "Russian Ruble",                           2, "₽"    },
                    { 114, "RWF", "Rwandan Franc",                           0, "Fr"   },
                    { 115, "SAR", "Saudi Riyal",                             2, "SR"   },
                    { 116, "SBD", "Solomon Islands Dollar",                  2, "$"    },
                    { 117, "SCR", "Seychellois Rupee",                       2, "₨"    },
                    { 118, "SDG", "Sudanese Pound",                          2, "ج.س"  },
                    { 119, "SEK", "Swedish Krona",                           2, "kr"   },
                    { 120, "SGD", "Singapore Dollar",                        2, "$"    },
                    { 121, "SHP", "Saint Helena Pound",                      2, "£"    },
                    { 122, "SLE", "Sierra Leonean Leone",                    2, "Le"   },
                    { 123, "SOS", "Somali Shilling",                         2, "Sh"   },
                    { 124, "SRD", "Surinamese Dollar",                       2, "$"    },
                    { 125, "SSP", "South Sudanese Pound",                    2, "£"    },
                    { 126, "STN", "São Tomé and Príncipe Dobra",             2, "Db"   },
                    { 127, "SYP", "Syrian Pound",                            2, "£"    },
                    { 128, "SZL", "Swazi Lilangeni",                         2, "L"    },
                    { 129, "THB", "Thai Baht",                               2, "฿"    },
                    { 130, "TJS", "Tajikistani Somoni",                      2, "SM"   },
                    { 131, "TMT", "Turkmenistan Manat",                      2, "T"    },
                    { 132, "TND", "Tunisian Dinar",                          3, "DT"   },
                    { 133, "TOP", "Tongan Paʻanga",                          2, "T$"   },
                    { 134, "TRY", "Turkish Lira",                            2, "₺"    },
                    { 135, "TTD", "Trinidad and Tobago Dollar",              2, "$"    },
                    { 136, "TWD", "New Taiwan Dollar",                       2, "$"    },
                    { 137, "TZS", "Tanzanian Shilling",                      2, "Sh"   },
                    { 138, "UAH", "Ukrainian Hryvnia",                       2, "₴"    },
                    { 139, "UGX", "Ugandan Shilling",                        0, "Sh"   },
                    { 140, "USD", "United States Dollar",                    2, "$"    },
                    { 141, "UYU", "Uruguayan Peso",                          2, "$"    },
                    { 142, "UZS", "Uzbekistani Som",                         2, "soʻm" },
                    { 143, "VES", "Venezuelan Bolívar Soberano",             2, "Bs.S" },
                    { 144, "VND", "Vietnamese Đồng",                         0, "₫"    },
                    { 145, "VUV", "Vanuatu Vatu",                            0, "Vt"   },
                    { 146, "WST", "Samoan Tala",                             2, "T"    },
                    { 147, "XAF", "Central African CFA Franc",               0, "Fr"   },
                    { 148, "XCD", "East Caribbean Dollar",                   2, "$"    },
                    { 149, "XOF", "West African CFA Franc",                  0, "Fr"   },
                    { 150, "XPF", "CFP Franc",                               0, "Fr"   },
                    { 151, "YER", "Yemeni Rial",                             2, "﷼"    },
                    { 152, "ZAR", "South African Rand",                      2, "R"    },
                    { 153, "ZMW", "Zambian Kwacha",                          2, "ZK"   },
                    { 154, "ZWG", "Zimbabwe Gold",                           2, "ZiG"  },
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "Currencies",
                keyColumn: "Id",
                keyValues: new object[]
                {
                      1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
                     11,  12,  13,  14,  15,  16,  17,  18,  19,  20,
                     21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
                     31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
                     41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
                     51,  52,  53,  54,  55,  56,  57,  58,  59,  60,
                     61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
                     71,  72,  73,  74,  75,  76,  77,  78,  79,  80,
                     81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
                     91,  92,  93,  94,  95,  96,  97,  98,  99, 100,
                    101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                    111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
                    121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
                    131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
                    141, 142, 143, 144, 145, 146, 147, 148, 149, 150,
                    151, 152, 153, 154
                });
        }
    }
}
