// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Touir.ExpensesManager.Expenses.Infrastructure;

#nullable disable

namespace Touir.ExpensesManager.Expenses.Migrations
{
    [DbContext(typeof(ExpensesDbContext))]
    partial class ExpensesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Touir.ExpensesManager.Expenses.Models.External.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("USR_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("USR_Email");

                    b.Property<int?>("FamilyId")
                        .HasColumnType("integer")
                        .HasColumnName("USR_FamilyId");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("USR_FirstName");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("USR_IsDeleted");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("USR_LastName");

                    b.HasKey("Id");

                    b.ToTable("USR_Users", "ext");
                });
#pragma warning restore 612, 618
        }
    }
}
