CREATE USER users WITH PASSWORD 'users';
GRANT ALL PRIVILEGES ON DATABASE users to users;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO users;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO users;
