CREATE USER gitlab WITH PASSWORD 'gitlab';
GRANT ALL PRIVILEGES ON DATABASE gitlab to gitlab;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO gitlab;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO gitlab;
GRANT CREATE, USAGE ON SCHEMA public TO gitlab;

