map $http_accept_language $lang {
  default en;
  ~fr fr;
  ~de de;
}

map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

map $sent_http_access_control_allow_origin $cors_origin {
  default "";
  "" "*";
}

map $sent_http_access_control_allow_methods $cors_methods {
  default "";
  "" "POST,PUT,GET,OPTIONS";
}

map $sent_http_access_control_allow_headers $cors_headers {
  default "";
  "" "Authorization, Content-Type";
}

server {
  listen 80;
  listen [::]:80;
  server_name expenses-manager;

  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;

  ssl_certificate /etc/nginx/ssl/expenses-manager.crt;
  ssl_certificate_key /etc/nginx/ssl/expenses-manager.key;
  ssl_protocols TLSv1.1 TLSv1.2;
  keepalive_timeout 70;
  add_header Strict-Transport-Security max-age=1209600;
  add_header X-Frame-Options sameorigin always;

  proxy_cookie_path / "/; HTTPOnly; Secure; SameSite=strict";

  root /usr/share/nginx/html;

  # auth_request /auth/check;

  location / {
    try_files $uri $uri/ @rewrites;
  }

  location @rewrites {
    # Can put some of your own rewrite rules in here
    # for example rewrite ^/~(.*)/(.*)/? /users/$1/$2 last;
    # If nothing matches we'll just send it to /index.html
    rewrite ^ /index.html last;
  }

#   location /auth/check {
#     proxy_pass http://auth:3002/check;
#     proxy_pass_request_body off;
#     proxy_set_header X-Original-Uri $request_uri;
#     proxy_set_header X-Original-Method $request_method;
#   }

  location /api/expenses/ {
    client_max_body_size 10M;
    #proxy_pass http://expenses:80/;
    proxy_pass https://host.docker.internal:8090/;

    #Enable CORS from any site
    add_header 'Access-Control-Allow-Origin' $cors_origin always;
    add_header 'Access-Control-Allow-Methods' $cors_methods always;
    add_header 'Access-Control-Allow-Headers' $cors_headers always;

    #Enable CORS preflight request
    if ($request_method = 'OPTIONS') {
      add_header 'Access-Control-Max-Age' '1728000';
      add_header 'Content-Type' 'text/plain charset=UTF-8';
      add_header 'Content-Length' '0';

      add_header 'Access-Control-Allow-Origin' $cors_origin always;
      add_header 'Access-Control-Allow-Methods' $cors_methods always;
      add_header 'Access-Control-Allow-Headers' $cors_headers always;
      return 204;
    }
  }

  location /api/users/ {
    client_max_body_size 10M;
    #proxy_pass http://users:80/;
	proxy_pass https://host.docker.internal:8100/;
	

    #Enable CORS from any site
    add_header 'Access-Control-Allow-Origin' $cors_origin always;
    add_header 'Access-Control-Allow-Methods' $cors_methods always;
    add_header 'Access-Control-Allow-Headers' $cors_headers always;

    #Enable CORS preflight request
    if ($request_method = 'OPTIONS') {
      add_header 'Access-Control-Max-Age' '1728000';
      add_header 'Content-Type' 'text/plain charset=UTF-8';
      add_header 'Content-Length' '0';

      add_header 'Access-Control-Allow-Origin' $cors_origin always;
      add_header 'Access-Control-Allow-Methods' $cors_methods always;
      add_header 'Access-Control-Allow-Headers' $cors_headers always;
      return 204;
    }
  }
}