# This is a GitLab CI/CD configuration file for deploying the Expense Manager application.

.deploy-web-dev:
  stage: deploy
  image: alpine:latest
  when: manual
  variables:
    ZIP_NAME_PREFIX: "expenses-manager-web"
  script:
    # Install tools
    - wget -q https://dl.min.io/client/mc/release/linux-amd64/mc -O /usr/bin/mc
    - chmod +x /usr/bin/mc
    - apk add --no-cache zip
    # Zip dist files with version
    - echo "Zipping dist files..."
    - VERSION=$(date +%Y%m%d%H%M%S)
    - ZIP_NAME="${ZIP_NAME_PREFIX}_$VERSION.zip"
    - cd dist
    - zip -r "/tmp/$ZIP_NAME" .
    # Upload zip to MinIO if credentials are set
    - mc alias set minio http://minio:9000 "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY"
    - mc mb --ignore-existing minio/expenses-manager-web-artifacts
    - mc mb --ignore-existing minio/expenses-manager-web
    - mc cp "/tmp/$ZIP_NAME" minio/expenses-manager-web-artifacts/
    - mc cp ./* minio/expenses-manager-web/ --recursive

.docker-deploy-dev:
  stage: deploy
  image: alpine:latest
  when: manual
  variables:
    IMAGE_VERSION: "latest"
    IMAGE_NAMER_PREFIX: "$CI_REGISTRY_IMAGE/"
  script:
    - apk add --no-cache curl
    - |
      if [ -z "$WATCHTOWER_API_TOKEN" ]; then
        echo "WATCHTOWER_API_TOKEN is not set."
        exit 1
      fi
    - |
      if [ -z "$IMAGE_NAME" ]; then
        echo "IMAGE_NAME variable is not set. Please set it in the CI configuration."
        exit 1
      fi
    - FULL_IMAGE_NAME="$IMAGE_NAMER_PREFIX$IMAGE_NAME:$IMAGE_VERSION"
    - echo "image = $FULL_IMAGE_NAME"
    # Trigger the update! We pass the specific image name so it only updates this app.
    - |
      curl -s -X GET \
        -H "Authorization: Bearer $WATCHTOWER_API_TOKEN" \
        "http://jobs-runner:8080/v1/update?image=$FULL_IMAGE_NAME"
