# GitLab CI configuration for initializing CI/CD pipelines for the Expense Manager project

variables:
  # Define any global variables for stages here if needed
  BASE_DIR_PATH: "."
  PROJECT_KEY: "expense-manager"
  IMAGE_NAME: ""

default:
  before_script:
    - cd $BASE_DIR_PATH