networks:
  expenses_manager_tools_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/24
  expense-management-apps_expenses_manager_apps_net:
    external: true

services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    networks:
      - expenses_manager_tools_net
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    environment:
      MP_DATABASE: "/var/lib/mailpit/data/mailpit.db"
      MP_LOG_FILE: "/var/lib/mailpit/logs/mailpit.log"
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    volumes:
      - ./volumes/mailpit/data:/var/lib/mailpit/data
      - ./volumes/mailpit/logs:/var/lib/mailpit/logs

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.9-management
    networks:
      - expenses_manager_tools_net
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management plugin port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./configs/rabbitmq:/etc/rabbitmq   # Mount custom configuration file
      - ./volumes/rabbitmq/data:/var/lib/rabbitmq
      - ./volumes/rabbitmq/logs:/var/log/rabbitmq
    command: rabbitmq-server
    
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.30.3
    networks:
      - expenses_manager_tools_net
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    container_name: grafana
    image: grafana/grafana:8.3.0
    networks:
      - expenses_manager_tools_net
    ports:
      - "3000:3000"
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
  
  postgres:
    image: postgres:16
    container_name: postgres
    networks:
      - expenses_manager_tools_net
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres/backups:/backups
      - ./volumes/postgres/data:/var/lib/postgresql/data
      
  redis:
    image: redis:7
    container_name: redis
    networks:
      - expenses_manager_tools_net
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis/data:/data
      
  minio:
    container_name: minio
    image: minio/minio
    command: server /data --console-address ":9050"
    networks:
      expenses_manager_tools_net:
        ipv4_address: 172.50.0.30
    ports:
      - "9001:9000" # MinIO S3 API
      - "9050:9050" # MinIO Console
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - ./volumes/minio/data:/data
      
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    networks:
      expenses_manager_tools_net:
        ipv4_address: 172.50.0.20
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: ${SONAR_DB_USER}
      SONAR_JDBC_PASSWORD: ${SONAR_DB_PASSWORD}
    volumes:
      - ./volumes/sonarqube/data:/opt/sonarqube/data
      - ./volumes/sonarqube/extensions:/opt/sonarqube/extensions
      - ./volumes/sonarqube/logs:/opt/sonarqube/logs
  
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: gitlab.local
    networks:
      expenses_manager_tools_net:
        ipv4_address: 172.50.0.10
    depends_on:
      - redis
      - postgres
      - minio
    ports:
      - "8500:8500"
      - "8443:443"
      - "2222:22"
      - "5050:5050"
    volumes:
      - ./configs/gitlab:/etc/gitlab
      - ./volumes/gitlab/logs:/var/log/gitlab
      - ./volumes/gitlab/data:/var/opt/gitlab
    shm_size: "256m"
    mem_limit: 4g
    cpus: 2
    environment:
      GITLAB_ROOT_PASSWORD: "${GITLAB_ROOT_PASSWORD}"
      GITLAB_OMNIBUS_CONFIG: |
        ### when using external reverse proxy
        letsencrypt['enable'] = false
        nginx['listen_port'] = 8500
        nginx['listen_https'] = false
        nginx['redirect_http_to_https'] = false
        nginx['gzip_enabled'] = false
        external_url 'http://localhost:8500'
        # Enable GitLab Container Registry
        gitlab_rails['registry_enabled'] = true
        registry['enable'] = true
        registry_external_url 'http://gitlab:5050'
        registry_nginx['listen_port'] = 5050
        registry_nginx['listen_https'] = false
        # Advertise a token auth realm reachable from containers
        registry['token_realm'] = 'http://gitlab:8500'
        registry['token_service'] = 'container_registry'
        registry['token_issuer'] = 'gitlab-issuer'
        postgresql['enable'] = false
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        gitlab_rails['db_database'] = 'gitlab'
        gitlab_rails['db_username'] = '${GITLAB_DB_USER}'
        gitlab_rails['db_password'] = '${GITLAB_DB_PASSWORD}'
        gitlab_rails['db_host'] = 'postgres'
        gitlab_rails['db_port'] = 5432
        redis['enable'] = false
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = 6379
        gitlab_rails['redis_database'] = 0
        prometheus['enable'] = false
        prometheus_monitoring['enable'] = false
        alertmanager['enable'] = false
        gitlab_rails['object_store']['enabled'] = true
        gitlab_rails['object_store']['connection'] = {
          'provider' => 'AWS',
          'aws_access_key_id' => '${MINIO_ACCESS_KEY}',
          'aws_secret_access_key' => '${MINIO_SECRET_KEY}',
          'region' => 'eu-west-1',
          'endpoint' => 'http://minio:9000',
          'path_style' => true
        }
        gitlab_rails['object_store']['objects']['artifacts'] = {
          'bucket' => 'gitlab-artifacts',
          'enabled' => true
        }
        gitlab_rails['object_store']['objects']['lfs'] = {
          'bucket' => 'gitlab-lfs',
          'enabled' => true
        }
        gitlab_rails['object_store']['objects']['packages'] = {
          'bucket' => 'gitlab-packages',
          'enabled' => true
        }
        gitlab_rails['object_store']['objects']['uploads'] = {
          'bucket' => 'gitlab-uploads',
          'enabled' => true
        }
        gitlab_rails['object_store']['objects']['registry'] = {
          'bucket' => 'gitlab-registry',
          'enabled' => true
        }
        gitlab_rails['object_store']['objects']['terraform_state'] = {
          'bucket' => 'gitlab-terraform-state',
          'enabled' => true
        }
        gitlab_rails['object_store']['objects']['dependency_proxy'] = {
          'bucket' => 'gitlab-dependency-proxy',
          'enabled' => true
        }
        gitlab_rails['object_store']['objects']['pages'] = {
          'bucket' => 'gitlab-pages',
          'enabled' => true
        }
        gitlab_rails['object_store']['objects']['ci_secure_files'] = {
          'bucket' => 'gitlab-ci-secure-files',
          'enabled' => true
        }
        gitlab_rails['object_store']['objects']['external_diffs'] = {
          'bucket' => 'gitlab-external-diffs',
          'enabled' => true
        }
        ### disable almost all optional services
        #gitlab_kas['enable'] = false
        #gitlab_rails['smtp_enable'] = false
        #gitlab_rails['microsoft_graph_mailer_enabled'] = false
        #mattermost['enable'] = false
        #mattermost_nginx['enable'] = false
        #postgres_exporter['enable'] = false
        #pgbouncer_exporter['enable'] = false
        #node_exporter['enable'] = false
        #redis_exporter['enable'] = false
        #monitoring_role['enable'] = false
        #gitlab_exporter['enable'] = false
        ### configure for low-memory usage
        puma['worker_processes'] = 1
        sidekiq['max_concurrency'] = 3
        ### disable service ping (telemetry)
        #gitlab_rails['usage_ping_enabled'] = false
        ### disable gitlab pages
        #gitlab_pages['enable'] = false
        ### disable mailroom
        #mailroom['enable'] = false

  docker-dind:
    image: docker:27-dind
    container_name: docker-dind
    privileged: true
    networks:
      - expenses_manager_tools_net
    environment:
      DOCKER_TLS_CERTDIR: ""
    command:
      - "--host=tcp://0.0.0.0:2375"
      - "--storage-driver=vfs"
    volumes:
      - dind-data:/var/lib/docker
    
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    networks:
      - expenses_manager_tools_net
    depends_on:
      - gitlab
      - docker-dind
    volumes:
      - ./configs/gitlab-runner:/gitlab-runner-config:ro
      - ./scripts:/runner-scripts:ro
      - runner-config-volume:/etc/gitlab-runner
    environment:
      CI_SERVER_URL: http://gitlab:8500
      DOCKER_HOST: tcp://docker-dind:2375
      DOCKER_TLS_CERTDIR: ""
      GITLAB_REGISTRATION_TOKEN: ${GITLAB_REGISTRATION_TOKEN}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    entrypoint: ["/bin/sh", "/runner-scripts/gitlab-register-runner.sh"]

  jobs-runner:
    build:
      context: ./jobs
    container_name: jobs-runner
    networks:
      expenses_manager_tools_net:
        ipv4_address: 172.50.0.40
      expense-management-apps_expenses_manager_apps_net: {}
    ports:
      - "9002:9002"
      - "8989:8989"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jobs/scripts:/opt/jobs/scripts:ro
      - ./jobs/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./jobs/configs:/opt/jobs/configs:ro
      - ./jobs/crontab:/etc/cron.d/jobs-runner-crontab:ro
      - ./volumes/jobs-runner/work:/work
      - ./volumes/jobs-runner/logs:/var/log
      - ./configs/ssh/id_ed25519:/root/.ssh/id_ed25519:ro
      - ./configs/ssh/known_hosts:/root/.ssh/known_hosts:ro
      - ./volumes/nginx/www:/shared
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      SUPERVISOR_USER: ${SUPERVISOR_USER}
      SUPERVISOR_PASS: ${SUPERVISOR_PASS}
      DOCKER_UPDATER_HTTP_API_TOKEN: ${DOCKER_UPDATER_HTTP_API_TOKEN}
      DOCKER_UPDATER_HTTP_API_PORT: "8989"
      DOCKER_REGISTRY_USER: ${DOCKER_REGISTRY_USER}
      DOCKER_REGISTRY_TOKEN: ${DOCKER_REGISTRY_TOKEN}
  
  
volumes:
  dind-data:
  runner-config-volume:
