networks:
  expenses_manager_apps_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.0.0/24

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    entrypoint: [ 'nginx', '-g', 'daemon off;' ]
    ports:
      - "80:80"
      - "443:443"
    networks:
      - expenses_manager_apps_net
    volumes:
      - ./configs/nginx:/etc/nginx
      - ./volumes/nginx/logs:/var/log/nginx
      - ./volumes/nginx/www:/usr/share/nginx/html
  
  users-service:
    image: localhost:5050/expenses-manager/expensemanager/expense-manager-backend-users:latest
    container_name: users-service
    pull_policy: always
    ports:
      - "9100:9100"
    environment:
      - ASPNETCORE_HTTP_PORTS=9100
      - EXPENSES_MANAGEMENT_USERS_DATABASE_SERVER=${EXPENSES_MANAGEMENT_USERS_DATABASE_SERVER}
      - EXPENSES_MANAGEMENT_USERS_DATABASE_PORT=${EXPENSES_MANAGEMENT_USERS_DATABASE_PORT}
      - EXPENSES_MANAGEMENT_USERS_DATABASE_USERNAME=${EXPENSES_MANAGEMENT_USERS_DATABASE_USERNAME}
      - EXPENSES_MANAGEMENT_USERS_DATABASE_PASSWORD=${EXPENSES_MANAGEMENT_USERS_DATABASE_PASSWORD}
      - EXPENSES_MANAGEMENT_USERS_DATABASE_DATABASE=${EXPENSES_MANAGEMENT_USERS_DATABASE_DATABASE}
      - EXPENSES_MANAGEMENT_USERS_JWT_SECRET_KEY=${EXPENSES_MANAGEMENT_USERS_JWT_SECRET_KEY}
      - EXPENSES_MANAGEMENT_USERS_JWT_EXPIRY_IN_MINUTES=${EXPENSES_MANAGEMENT_USERS_JWT_EXPIRY_IN_MINUTES}
      - EXPENSES_MANAGEMENT_USERS_JWT_AUDIENCE=${EXPENSES_MANAGEMENT_USERS_JWT_AUDIENCE}
      - EXPENSES_MANAGEMENT_USERS_JWT_ISSUER=${EXPENSES_MANAGEMENT_USERS_JWT_ISSUER}
      - EXPENSES_MANAGEMENT_USERS_EMAILAUTH_EMAIL=${EXPENSES_MANAGEMENT_USERS_EMAILAUTH_EMAIL}
      - EXPENSES_MANAGEMENT_USERS_EMAILAUTH_PASSWORD=${EXPENSES_MANAGEMENT_USERS_EMAILAUTH_PASSWORD}
      - EXPENSES_MANAGEMENT_USERS_EMAILAUTH_HOST=${EXPENSES_MANAGEMENT_USERS_EMAILAUTH_HOST}
      - EXPENSES_MANAGEMENT_USERS_EMAILAUTH_PORT=${EXPENSES_MANAGEMENT_USERS_EMAILAUTH_PORT}
      - EXPENSES_MANAGEMENT_USERS_AUTHSERVICE_VERIFY_EMAIL_URL=${EXPENSES_MANAGEMENT_USERS_AUTHSERVICE_VERIFY_EMAIL_URL}
      - EXPENSES_MANAGEMENT_CRYPTOGRAPHY_MAXIMUM_SALT_SIZE=${EXPENSES_MANAGEMENT_CRYPTOGRAPHY_MAXIMUM_SALT_SIZE}
    networks:
      - expenses_manager_apps_net
