global:
  scrape_interval: 15s   # Scrape targets every 15 seconds

scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']   # RabbitMQ management plugin port

  # Add more scrape configurations for other targets as needed