// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using com.touir.expenses.Users.Infrastructure;

#nullable disable

namespace com.touir.expenses.Users.Migrations
{
    [DbContext(typeof(UsersAppDbContext))]
    [Migration("20251225160934_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("com.touir.expenses.Users.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("APP_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("APP_Code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("APP_Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("APP_Name");

                    b.Property<string>("UrlPath")
                        .HasColumnType("text")
                        .HasColumnName("APP_UrlPath");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("APP_Applications", (string)null);
                });

            modelBuilder.Entity("com.touir.expenses.Users.Models.Authentication", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("ATH_UserId");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ATH_HashPassword");

                    b.Property<string>("HashSalt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ATH_HashSalt");

                    b.Property<bool>("IsTemporaryPassword")
                        .HasColumnType("boolean")
                        .HasColumnName("ATH_IsTemporaryPassword");

                    b.Property<string>("PasswordResetHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ATH_PasswordResetHash");

                    b.Property<DateTime?>("PasswordResetRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ATH_PasswordResetRequestedAt");

                    b.HasKey("UserId");

                    b.ToTable("ATH_Authentications", (string)null);
                });

            modelBuilder.Entity("com.touir.expenses.Users.Models.RequestAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RQA_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("RQA_ApplicationId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RQA_Description");

                    b.Property<bool>("IsAuthenticationNeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("RQA_IsAuthenticationNeeded");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RQA_Name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RQA_Path");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RQA_Type");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("RQA_RequestAccesses", (string)null);
                });

            modelBuilder.Entity("com.touir.expenses.Users.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RLE_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("RLE_ApplicationId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RLE_Code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RLE_Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RLE_Name");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("RLE_Roles", (string)null);
                });

            modelBuilder.Entity("com.touir.expenses.Users.Models.RoleRequestAccess", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("RRA_RoleId");

                    b.Property<int>("RequestAccessId")
                        .HasColumnType("integer")
                        .HasColumnName("RRA_RequestAccessId");

                    b.HasKey("RoleId", "RequestAccessId");

                    b.HasIndex("RequestAccessId");

                    b.ToTable("RRA_RoleRequestAccesses", (string)null);
                });

            modelBuilder.Entity("com.touir.expenses.Users.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("USR_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("USR_CreatedAt");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("USR_CreatedBy");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("USR_Email");

                    b.Property<string>("EmailValidationHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("USR_EmailValidationHash");

                    b.Property<int?>("FamilyId")
                        .HasColumnType("integer")
                        .HasColumnName("USR_FamilyId");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("USR_FirstName");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("USR_IsDisabled");

                    b.Property<bool>("IsEmailValidated")
                        .HasColumnType("boolean")
                        .HasColumnName("USR_IsEmailValidated");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("USR_LastName");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("USR_LastUpdatedAt");

                    b.Property<int?>("LastUpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("USR_LastUpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastUpdatedById");

                    b.ToTable("USR_Users", (string)null);
                });

            modelBuilder.Entity("com.touir.expenses.Users.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("URR_UserId");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("URR_RoleId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("URR_CreatedAt");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("URR_CreatedById");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("RoleId");

                    b.ToTable("URR_UserRoles", (string)null);
                });

            modelBuilder.Entity("com.touir.expenses.Users.Models.Authentication", b =>
                {
                    b.HasOne("com.touir.expenses.Users.Models.User", "User")
                        .WithOne("Authentication")
                        .HasForeignKey("com.touir.expenses.Users.Models.Authentication", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("com.touir.expenses.Users.Models.RequestAccess", b =>
                {
                    b.HasOne("com.touir.expenses.Users.Models.Application", "Application")
                        .WithMany("RequestAccesses")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("com.touir.expenses.Users.Models.Role", b =>
                {
                    b.HasOne("com.touir.expenses.Users.Models.Application", "Application")
                        .WithMany("Roles")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("com.touir.expenses.Users.Models.RoleRequestAccess", b =>
                {
                    b.HasOne("com.touir.expenses.Users.Models.RequestAccess", "RequestAccess")
                        .WithMany("RoleRequestAccesses")
                        .HasForeignKey("RequestAccessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("com.touir.expenses.Users.Models.Role", "Role")
                        .WithMany("RoleRequestAccesses")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequestAccess");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("com.touir.expenses.Users.Models.User", b =>
                {
                    b.HasOne("com.touir.expenses.Users.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("com.touir.expenses.Users.Models.User", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("LastUpdatedBy");
                });

            modelBuilder.Entity("com.touir.expenses.Users.Models.UserRole", b =>
                {
                    b.HasOne("com.touir.expenses.Users.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("com.touir.expenses.Users.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("com.touir.expenses.Users.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("com.touir.expenses.Users.Models.Application", b =>
                {
                    b.Navigation("RequestAccesses");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("com.touir.expenses.Users.Models.RequestAccess", b =>
                {
                    b.Navigation("RoleRequestAccesses");
                });

            modelBuilder.Entity("com.touir.expenses.Users.Models.Role", b =>
                {
                    b.Navigation("RoleRequestAccesses");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("com.touir.expenses.Users.Models.User", b =>
                {
                    b.Navigation("Authentication")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
